server:
  http_listen_port: 3101
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # Scrape Docker container logs
  - job_name: docker
    static_configs:
      - targets:
          - localhost
        labels:
          job: docker
          __path__: /var/lib/docker/containers/*/*.log

  # Scrape application logs
  - job_name: devops-hello
    static_configs:
      - targets:
          - localhost
        labels:
          job: devops-hello
          app: hello-app
          __path__: /var/log/app/*.log

  # Scrape system logs
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: system
          __path__: /var/log/*.log
